coverage:
  all_nodes: 0
  covered_nodes: 0
mutation_score: 100.0
mutations:
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Chain_of_thought2\\tests\\test_096.py\", line 9, in test_back_to_back_occurrences\n\
    \    def test_back_to_back_occurrences(self): self.assertEqual(count_occurance('stdstd'),\
    \ 2)\n  File \"datasets.GPT_4.Chain_of_thought2.programs.program_096\", line 4,\
    \ in count_occurance\nIndexError: string index out of range\n"
  killer: test_back_to_back_occurrences (datasets.GPT_4.Chain_of_thought2.tests.test_096.TestVersion)
  module: &id001 !!python/module:datasets.GPT_4.Chain_of_thought2.programs.program_096 ''
  mutations:
  - lineno: 3
    operator: AOR
  number: 1
  status: killed
  tests_run: 1
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Chain_of_thought2\\tests\\test_096.py\", line 9, in test_back_to_back_occurrences\n\
    \    def test_back_to_back_occurrences(self): self.assertEqual(count_occurance('stdstd'),\
    \ 2)\nAssertionError: 0 != 2\n"
  killer: test_back_to_back_occurrences (datasets.GPT_4.Chain_of_thought2.tests.test_096.TestVersion)
  module: *id001
  mutations:
  - lineno: 4
    operator: AOR
  number: 2
  status: killed
  tests_run: 1
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Chain_of_thought2\\tests\\test_096.py\", line 9, in test_back_to_back_occurrences\n\
    \    def test_back_to_back_occurrences(self): self.assertEqual(count_occurance('stdstd'),\
    \ 2)\nAssertionError: 0 != 2\n"
  killer: test_back_to_back_occurrences (datasets.GPT_4.Chain_of_thought2.tests.test_096.TestVersion)
  module: *id001
  mutations:
  - lineno: 4
    operator: AOR
  number: 3
  status: killed
  tests_run: 1
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Chain_of_thought2\\tests\\test_096.py\", line 9, in test_back_to_back_occurrences\n\
    \    def test_back_to_back_occurrences(self): self.assertEqual(count_occurance('stdstd'),\
    \ 2)\nAssertionError: -2 != 2\n"
  killer: test_back_to_back_occurrences (datasets.GPT_4.Chain_of_thought2.tests.test_096.TestVersion)
  module: *id001
  mutations:
  - lineno: 5
    operator: AOR
  number: 4
  status: killed
  tests_run: 1
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Chain_of_thought2\\tests\\test_096.py\", line 21, in test_case_sensitivity\n \
    \   def test_case_sensitivity(self): self.assertEqual(count_occurance('StdSTDstd'),\
    \ 1)\nAssertionError: 6 != 1\n"
  killer: test_case_sensitivity (datasets.GPT_4.Chain_of_thought2.tests.test_096.TestVersion)
  module: *id001
  mutations:
  - lineno: 4
    operator: COI
  number: 5
  status: killed
  tests_run: 2
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Chain_of_thought2\\tests\\test_096.py\", line 21, in test_case_sensitivity\n \
    \   def test_case_sensitivity(self): self.assertEqual(count_occurance('StdSTDstd'),\
    \ 1)\nAssertionError: 2 != 1\n"
  killer: test_case_sensitivity (datasets.GPT_4.Chain_of_thought2.tests.test_096.TestVersion)
  module: *id001
  mutations:
  - lineno: 4
    operator: LCR
  number: 6
  status: killed
  tests_run: 2
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Chain_of_thought2\\tests\\test_096.py\", line 9, in test_back_to_back_occurrences\n\
    \    def test_back_to_back_occurrences(self): self.assertEqual(count_occurance('stdstd'),\
    \ 2)\nAssertionError: 0 != 2\n"
  killer: test_back_to_back_occurrences (datasets.GPT_4.Chain_of_thought2.tests.test_096.TestVersion)
  module: *id001
  mutations:
  - lineno: 4
    operator: ROR
  number: 7
  status: killed
  tests_run: 1
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Chain_of_thought2\\tests\\test_096.py\", line 9, in test_back_to_back_occurrences\n\
    \    def test_back_to_back_occurrences(self): self.assertEqual(count_occurance('stdstd'),\
    \ 2)\nAssertionError: 0 != 2\n"
  killer: test_back_to_back_occurrences (datasets.GPT_4.Chain_of_thought2.tests.test_096.TestVersion)
  module: *id001
  mutations:
  - lineno: 4
    operator: ROR
  number: 8
  status: killed
  tests_run: 1
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Chain_of_thought2\\tests\\test_096.py\", line 9, in test_back_to_back_occurrences\n\
    \    def test_back_to_back_occurrences(self): self.assertEqual(count_occurance('stdstd'),\
    \ 2)\nAssertionError: 0 != 2\n"
  killer: test_back_to_back_occurrences (datasets.GPT_4.Chain_of_thought2.tests.test_096.TestVersion)
  module: *id001
  mutations:
  - lineno: 4
    operator: ROR
  number: 9
  status: killed
  tests_run: 1
  time: 0.015701770782470703
number_of_tests: 10
targets:
- datasets.GPT_4.Chain_of_thought2.programs.program_096
tests:
- name: datasets.GPT_4.Chain_of_thought2.tests.test_096
  target: null
  time: 0.0
time_stats:
  create_mutant_module: 0.0
  create_target_ast: 0.0
  mutate_module: 0.06298613548278809
  run_tests_with_mutant: 0.015701770782470703
total_time: 0.07862281799316406
