coverage:
  all_nodes: 0
  covered_nodes: 0
mutation_score: 88.88888888888889
mutations:
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Chain_of_thought\\tests\\test_020.py\", line 33, in test_floating_point_numbers\n\
    \    self.assertTrue(is_Monotonic([1.1, 2.2, 3.3]))\nAssertionError: False is\
    \ not true\n"
  killer: test_floating_point_numbers (datasets.GPT_4.Chain_of_thought.tests.test_020.TestVersion)
  module: &id001 !!python/module:datasets.GPT_4.Chain_of_thought.programs.program_020 ''
  mutations:
  - lineno: 2
    operator: AOR
  number: 1
  status: killed
  tests_run: 4
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Chain_of_thought\\tests\\test_020.py\", line 12, in test_constant_sequence\n \
    \   self.assertTrue(is_Monotonic([3, 3, 3, 3]))\n  File \"datasets.GPT_4.Chain_of_thought.programs.program_020\"\
    , line 2, in is_Monotonic\n  File \"datasets.GPT_4.Chain_of_thought.programs.program_020\"\
    , line 2, in <genexpr>\nIndexError: list index out of range\n"
  killer: test_constant_sequence (datasets.GPT_4.Chain_of_thought.tests.test_020.TestVersion)
  module: *id001
  mutations:
  - lineno: 2
    operator: AOR
  number: 2
  status: killed
  tests_run: 2
  time: 0.002597808837890625
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Chain_of_thought\\tests\\test_020.py\", line 9, in test_strictly_decreasing\n\
    \    self.assertTrue(is_Monotonic([5, 4, 3, 2, 1]))\nAssertionError: False is\
    \ not true\n"
  killer: test_strictly_decreasing (datasets.GPT_4.Chain_of_thought.tests.test_020.TestVersion)
  module: *id001
  mutations:
  - lineno: 3
    operator: AOR
  number: 3
  status: killed
  tests_run: 9
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Chain_of_thought\\tests\\test_020.py\", line 39, in test_boundary_values\n   \
    \ self.assertTrue(is_Monotonic([2147483647, 2147483647, 2147483646]))\n  File\
    \ \"datasets.GPT_4.Chain_of_thought.programs.program_020\", line 3, in is_Monotonic\n\
    \  File \"datasets.GPT_4.Chain_of_thought.programs.program_020\", line 3, in <genexpr>\n\
    IndexError: list index out of range\n"
  killer: test_boundary_values (datasets.GPT_4.Chain_of_thought.tests.test_020.TestVersion)
  module: *id001
  mutations:
  - lineno: 3
    operator: AOR
  number: 4
  status: killed
  tests_run: 1
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Chain_of_thought\\tests\\test_020.py\", line 39, in test_boundary_values\n   \
    \ self.assertTrue(is_Monotonic([2147483647, 2147483647, 2147483646]))\nAssertionError:\
    \ False is not true\n"
  killer: test_boundary_values (datasets.GPT_4.Chain_of_thought.tests.test_020.TestVersion)
  module: *id001
  mutations:
  - lineno: 2
    operator: LCR
  number: 5
  status: killed
  tests_run: 1
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Chain_of_thought\\tests\\test_020.py\", line 33, in test_floating_point_numbers\n\
    \    self.assertTrue(is_Monotonic([1.1, 2.2, 3.3]))\nAssertionError: False is\
    \ not true\n"
  killer: test_floating_point_numbers (datasets.GPT_4.Chain_of_thought.tests.test_020.TestVersion)
  module: *id001
  mutations:
  - lineno: 2
    operator: ROR
  number: 6
  status: killed
  tests_run: 4
  time: 0.0
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 2
    operator: ROR
  number: 7
  status: survived
  tests_run: 12
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Chain_of_thought\\tests\\test_020.py\", line 39, in test_boundary_values\n   \
    \ self.assertTrue(is_Monotonic([2147483647, 2147483647, 2147483646]))\nAssertionError:\
    \ False is not true\n"
  killer: test_boundary_values (datasets.GPT_4.Chain_of_thought.tests.test_020.TestVersion)
  module: *id001
  mutations:
  - lineno: 3
    operator: ROR
  number: 8
  status: killed
  tests_run: 1
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Chain_of_thought\\tests\\test_020.py\", line 39, in test_boundary_values\n   \
    \ self.assertTrue(is_Monotonic([2147483647, 2147483647, 2147483646]))\nAssertionError:\
    \ False is not true\n"
  killer: test_boundary_values (datasets.GPT_4.Chain_of_thought.tests.test_020.TestVersion)
  module: *id001
  mutations:
  - lineno: 3
    operator: ROR
  number: 9
  status: killed
  tests_run: 1
  time: 0.0
number_of_tests: 12
targets:
- datasets.GPT_4.Chain_of_thought.programs.program_020
tests:
- name: datasets.GPT_4.Chain_of_thought.tests.test_020
  target: null
  time: 0.0
time_stats:
  create_mutant_module: 0.0
  create_target_ast: 0.009092330932617188
  mutate_module: 0.07237887382507324
  run_tests_with_mutant: 0.002597808837890625
total_time: 0.07237887382507324
