coverage:
  all_nodes: 0
  covered_nodes: 0
mutation_score: 100.0
mutations:
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Zero_shot\\tests\\test_048.py\", line 13, in test_multiple_spaces_2\n    assert\
    \ next_smallest_palindrome(num) == expected_output\nAssertionError\n"
  killer: test_multiple_spaces_2 (datasets.GPT_4.Zero_shot.tests.test_048.TestVersion)
  module: &id001 !!python/module:datasets.GPT_4.Zero_shot.programs.program_048 ''
  mutations:
  - lineno: 5
    operator: AOD
  number: 1
  status: killed
  tests_run: 2
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Zero_shot\\tests\\test_048.py\", line 8, in test_multiple_spaces\n    assert next_smallest_palindrome(num)\
    \ == expected_output\nAssertionError\n"
  killer: test_multiple_spaces (datasets.GPT_4.Zero_shot.tests.test_048.TestVersion)
  module: *id001
  mutations:
  - lineno: 4
    operator: AOR
  number: 2
  status: killed
  tests_run: 1
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Zero_shot\\tests\\test_048.py\", line 13, in test_multiple_spaces_2\n    assert\
    \ next_smallest_palindrome(num) == expected_output\nAssertionError\n"
  killer: test_multiple_spaces_2 (datasets.GPT_4.Zero_shot.tests.test_048.TestVersion)
  module: *id001
  mutations:
  - lineno: 5
    operator: AOR
  number: 3
  status: killed
  tests_run: 2
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Zero_shot\\tests\\test_048.py\", line 8, in test_multiple_spaces\n    assert next_smallest_palindrome(num)\
    \ == expected_output\nAssertionError\n"
  killer: test_multiple_spaces (datasets.GPT_4.Zero_shot.tests.test_048.TestVersion)
  module: *id001
  mutations:
  - lineno: 5
    operator: COI
  number: 4
  status: killed
  tests_run: 1
  time: 0.01001286506652832
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Zero_shot\\tests\\test_048.py\", line 8, in test_multiple_spaces\n    assert next_smallest_palindrome(num)\
    \ == expected_output\nAssertionError\n"
  killer: test_multiple_spaces (datasets.GPT_4.Zero_shot.tests.test_048.TestVersion)
  module: *id001
  mutations:
  - lineno: 5
    operator: ROR
  number: 5
  status: killed
  tests_run: 1
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Zero_shot\\tests\\test_048.py\", line 13, in test_multiple_spaces_2\n    assert\
    \ next_smallest_palindrome(num) == expected_output\nAssertionError\n"
  killer: test_multiple_spaces_2 (datasets.GPT_4.Zero_shot.tests.test_048.TestVersion)
  module: *id001
  mutations:
  - lineno: 5
    operator: SIR
  number: 6
  status: killed
  tests_run: 2
  time: 0.0
number_of_tests: 8
targets:
- datasets.GPT_4.Zero_shot.programs.program_048
tests:
- name: datasets.GPT_4.Zero_shot.tests.test_048
  target: null
  time: 0.0
time_stats:
  create_mutant_module: 0.0
  create_target_ast: 0.0
  mutate_module: 0.04933571815490723
  run_tests_with_mutant: 0.01001286506652832
total_time: 0.04933571815490723
