coverage:
  all_nodes: 0
  covered_nodes: 0
mutation_score: 100.0
mutations:
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Zero_shot\\tests\\test_033.py\", line 13, in test_multiple_spaces_2\n    assert\
    \ surfacearea_sphere(r) == expected_output\nAssertionError\n"
  killer: test_multiple_spaces_2 (datasets.GPT_4.Zero_shot.tests.test_033.TestVersion)
  module: &id001 !!python/module:datasets.GPT_4.Zero_shot.programs.program_033 ''
  mutations:
  - lineno: 3
    operator: AOR
  number: 1
  status: killed
  tests_run: 2
  time: 0.0010149478912353516
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Zero_shot\\tests\\test_033.py\", line 13, in test_multiple_spaces_2\n    assert\
    \ surfacearea_sphere(r) == expected_output\nAssertionError\n"
  killer: test_multiple_spaces_2 (datasets.GPT_4.Zero_shot.tests.test_033.TestVersion)
  module: *id001
  mutations:
  - lineno: 3
    operator: AOR
  number: 2
  status: killed
  tests_run: 2
  time: 0.0009462833404541016
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Zero_shot\\tests\\test_033.py\", line 13, in test_multiple_spaces_2\n    assert\
    \ surfacearea_sphere(r) == expected_output\nAssertionError\n"
  killer: test_multiple_spaces_2 (datasets.GPT_4.Zero_shot.tests.test_033.TestVersion)
  module: *id001
  mutations:
  - lineno: 3
    operator: AOR
  number: 3
  status: killed
  tests_run: 2
  time: 0.0005922317504882812
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Zero_shot\\tests\\test_033.py\", line 8, in test_multiple_spaces\n    assert surfacearea_sphere(r)\
    \ == expected_output\n  File \"datasets.GPT_4.Zero_shot.programs.program_033\"\
    , line 3, in surfacearea_sphere\nZeroDivisionError: float division by zero\n"
  killer: test_multiple_spaces (datasets.GPT_4.Zero_shot.tests.test_033.TestVersion)
  module: *id001
  mutations:
  - lineno: 3
    operator: AOR
  number: 4
  status: killed
  tests_run: 1
  time: 0.002002716064453125
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Zero_shot\\tests\\test_033.py\", line 8, in test_multiple_spaces\n    assert surfacearea_sphere(r)\
    \ == expected_output\n  File \"datasets.GPT_4.Zero_shot.programs.program_033\"\
    , line 3, in surfacearea_sphere\nZeroDivisionError: float divmod()\n"
  killer: test_multiple_spaces (datasets.GPT_4.Zero_shot.tests.test_033.TestVersion)
  module: *id001
  mutations:
  - lineno: 3
    operator: AOR
  number: 5
  status: killed
  tests_run: 1
  time: 0.0010004043579101562
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Zero_shot\\tests\\test_033.py\", line 18, in test_multiple_spaces_3\n    assert\
    \ surfacearea_sphere(r) == expected_output\nAssertionError\n"
  killer: test_multiple_spaces_3 (datasets.GPT_4.Zero_shot.tests.test_033.TestVersion)
  module: *id001
  mutations:
  - lineno: 3
    operator: AOR
  number: 6
  status: killed
  tests_run: 3
  time: 0.0009908676147460938
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Zero_shot\\tests\\test_033.py\", line 8, in test_multiple_spaces\n    assert surfacearea_sphere(r)\
    \ == expected_output\n  File \"datasets.GPT_4.Zero_shot.programs.program_033\"\
    , line 3, in surfacearea_sphere\nZeroDivisionError: float division by zero\n"
  killer: test_multiple_spaces (datasets.GPT_4.Zero_shot.tests.test_033.TestVersion)
  module: *id001
  mutations:
  - lineno: 3
    operator: AOR
  number: 7
  status: killed
  tests_run: 1
  time: 0.0020198822021484375
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Zero_shot\\tests\\test_033.py\", line 8, in test_multiple_spaces\n    assert surfacearea_sphere(r)\
    \ == expected_output\n  File \"datasets.GPT_4.Zero_shot.programs.program_033\"\
    , line 3, in surfacearea_sphere\nZeroDivisionError: float divmod()\n"
  killer: test_multiple_spaces (datasets.GPT_4.Zero_shot.tests.test_033.TestVersion)
  module: *id001
  mutations:
  - lineno: 3
    operator: AOR
  number: 8
  status: killed
  tests_run: 1
  time: 0.0019407272338867188
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Zero_shot\\tests\\test_033.py\", line 8, in test_multiple_spaces\n    assert surfacearea_sphere(r)\
    \ == expected_output\nAssertionError\n"
  killer: test_multiple_spaces (datasets.GPT_4.Zero_shot.tests.test_033.TestVersion)
  module: *id001
  mutations:
  - lineno: 3
    operator: AOR
  number: 9
  status: killed
  tests_run: 1
  time: 0.0010008811950683594
number_of_tests: 6
targets:
- datasets.GPT_4.Zero_shot.programs.program_033
tests:
- name: datasets.GPT_4.Zero_shot.tests.test_033
  target: null
  time: 0.0
time_stats:
  create_mutant_module: 0.0
  create_target_ast: 0.0009479522705078125
  mutate_module: 0.05923008918762207
  run_tests_with_mutant: 0.01401066780090332
total_time: 0.06570148468017578
