[*] Start mutation process:
   - targets: datasets.GPT_4.Few_shot.programs.program_097
   - tests: datasets.GPT_4.Few_shot.tests.test_097
[*] 8 tests passed:
   - datasets.GPT_4.Few_shot.tests.test_097 [0.00000 s]
[*] Start mutants generation and execution:
   - [#   1] BCR datasets.GPT_4.Few_shot.programs.program_097: [0.00000 s] survived
   - [#   2] COD datasets.GPT_4.Few_shot.programs.program_097: [0.00000 s] killed by test_case_1 (datasets.GPT_4.Few_shot.tests.test_097.TestVersion)

Traceback (most recent call last):
  File "C:\Users\skaspers\OneDrive - Capgemini\Documents\Prompted Testsuite Analysis\.\datasets\GPT_4\Few_shot\tests\test_097.py", line 6, in test_case_1
    self.assertEqual(check_type((1, 2, 3)), True) # All integers)
AssertionError: False != True

   - [#   3] COI datasets.GPT_4.Few_shot.programs.program_097: [0.00000 s] killed by test_case_1 (datasets.GPT_4.Few_shot.tests.test_097.TestVersion)

Traceback (most recent call last):
  File "C:\Users\skaspers\OneDrive - Capgemini\Documents\Prompted Testsuite Analysis\.\datasets\GPT_4\Few_shot\tests\test_097.py", line 6, in test_case_1
    self.assertEqual(check_type((1, 2, 3)), True) # All integers)
AssertionError: False != True

[*] Mutation score [0.05022 s]: 66.7%
   - all: 3
   - killed: 2 (66.7%)
   - survived: 1 (33.3%)
   - incompetent: 0 (0.0%)
   - timeout: 0 (0.0%)
HI SANDER, RUNNING MUTPY FROM: C:\Users\skaspers\OneDrive - Capgemini\Documents\Prompted Testsuite Analysis\.venv38\lib\site-packages\mutpy\commandline.py
