[*] Start mutation process:
   - targets: datasets.GPT_4.Few_shot2.programs.program_086
   - tests: datasets.GPT_4.Few_shot2.tests.test_086
[*] 9 tests passed:
   - datasets.GPT_4.Few_shot2.tests.test_086 [0.00000 s]
[*] Start mutants generation and execution:
   - [#   1] COD datasets.GPT_4.Few_shot2.programs.program_086: [0.00000 s] killed by test_remove_elements_all_removed (datasets.GPT_4.Few_shot2.tests.test_086.TestVersion)

Traceback (most recent call last):
  File "C:\Users\skaspers\OneDrive - Capgemini\Documents\Prompted Testsuite Analysis\.\datasets\GPT_4\Few_shot2\tests\test_086.py", line 7, in test_remove_elements_all_removed
    def test_remove_elements_all_removed(self): self.assertEqual(remove_elements([1, 2], [1, 2]), [])
AssertionError: Lists differ: [1, 2] != []

First list contains 2 additional elements.
First extra element 0:
1

- [1, 2]
+ []

[*] Mutation score [0.03181 s]: 100.0%
   - all: 1
   - killed: 1 (100.0%)
   - survived: 0 (0.0%)
   - incompetent: 0 (0.0%)
   - timeout: 0 (0.0%)
HI SANDER, RUNNING MUTPY FROM: C:\Users\skaspers\OneDrive - Capgemini\Documents\Prompted Testsuite Analysis\.venv38\lib\site-packages\mutpy\commandline.py
