coverage:
  all_nodes: 0
  covered_nodes: 0
mutation_score: 94.44444444444444
mutations:
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\mbpp\\\
    tests\\test_021.py\", line 9, in test_is_sublist_with_2_4_3_5_7_4_3_expect_True\n\
    \    self.assertEqual(is_sublist([2,4,3,5,7],[4,3]), True)\nAssertionError: False\
    \ != True\n"
  killer: test_is_sublist_with_2_4_3_5_7_4_3_expect_True (datasets.mbpp.tests.test_021.TestVersion)
  module: &id001 !!python/module:datasets.mbpp.programs.program_021 ''
  mutations:
  - lineno: 13
    operator: AOR
  number: 1
  status: killed
  tests_run: 3
  time: 0.0009963512420654297
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\mbpp\\\
    tests\\test_021.py\", line 9, in test_is_sublist_with_2_4_3_5_7_4_3_expect_True\n\
    \    self.assertEqual(is_sublist([2,4,3,5,7],[4,3]), True)\nAssertionError: False\
    \ != True\n"
  killer: test_is_sublist_with_2_4_3_5_7_4_3_expect_True (datasets.mbpp.tests.test_021.TestVersion)
  module: *id001
  mutations:
  - lineno: 14
    operator: ASR
  number: 2
  status: killed
  tests_run: 3
  time: 0.0010180473327636719
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\mbpp\\\
    tests\\test_021.py\", line 12, in test_is_sublist_with_2_4_3_5_7_1_6_expect_False\n\
    \    self.assertEqual(is_sublist([2,4,3,5,7],[1,6]), False)\nAssertionError: True\
    \ != False\n"
  killer: test_is_sublist_with_2_4_3_5_7_1_6_expect_False (datasets.mbpp.tests.test_021.TestVersion)
  module: *id001
  mutations:
  - lineno: 3
    operator: COI
  number: 3
  status: killed
  tests_run: 1
  time: 0.0010216236114501953
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\mbpp\\\
    tests\\test_021.py\", line 12, in test_is_sublist_with_2_4_3_5_7_1_6_expect_False\n\
    \    self.assertEqual(is_sublist([2,4,3,5,7],[1,6]), False)\nAssertionError: True\
    \ != False\n"
  killer: test_is_sublist_with_2_4_3_5_7_1_6_expect_False (datasets.mbpp.tests.test_021.TestVersion)
  module: *id001
  mutations:
  - lineno: 5
    operator: COI
  number: 4
  status: killed
  tests_run: 1
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\mbpp\\\
    tests\\test_021.py\", line 9, in test_is_sublist_with_2_4_3_5_7_4_3_expect_True\n\
    \    self.assertEqual(is_sublist([2,4,3,5,7],[4,3]), True)\nAssertionError: False\
    \ != True\n"
  killer: test_is_sublist_with_2_4_3_5_7_4_3_expect_True (datasets.mbpp.tests.test_021.TestVersion)
  module: *id001
  mutations:
  - lineno: 7
    operator: COI
  number: 5
  status: killed
  tests_run: 3
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\mbpp\\\
    tests\\test_021.py\", line 12, in test_is_sublist_with_2_4_3_5_7_1_6_expect_False\n\
    \    self.assertEqual(is_sublist([2,4,3,5,7],[1,6]), False)\n  File \"datasets.mbpp.programs.program_021\"\
    , line 13, in is_sublist\nIndexError: list index out of range\n"
  killer: test_is_sublist_with_2_4_3_5_7_1_6_expect_False (datasets.mbpp.tests.test_021.TestVersion)
  module: *id001
  mutations:
  - lineno: 11
    operator: COI
  number: 6
  status: killed
  tests_run: 1
  time: 0.0009975433349609375
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 13
    operator: COI
  number: 7
  status: timeout
  tests_run: null
  time: 5.03985857963562
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\mbpp\\\
    tests\\test_021.py\", line 6, in test_is_sublist_with_2_4_3_5_7_3_7_expect_False\n\
    \    self.assertEqual(is_sublist([2,4,3,5,7],[3,7]), False)\nAssertionError: True\
    \ != False\n"
  killer: test_is_sublist_with_2_4_3_5_7_3_7_expect_False (datasets.mbpp.tests.test_021.TestVersion)
  module: *id001
  mutations:
  - lineno: 15
    operator: COI
  number: 8
  status: killed
  tests_run: 2
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\mbpp\\\
    tests\\test_021.py\", line 6, in test_is_sublist_with_2_4_3_5_7_3_7_expect_False\n\
    \    self.assertEqual(is_sublist([2,4,3,5,7],[3,7]), False)\n  File \"datasets.mbpp.programs.program_021\"\
    , line 13, in is_sublist\nIndexError: list index out of range\n"
  killer: test_is_sublist_with_2_4_3_5_7_3_7_expect_False (datasets.mbpp.tests.test_021.TestVersion)
  module: *id001
  mutations:
  - lineno: 13
    operator: LCR
  number: 9
  status: killed
  tests_run: 2
  time: 0.0016193389892578125
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\mbpp\\\
    tests\\test_021.py\", line 12, in test_is_sublist_with_2_4_3_5_7_1_6_expect_False\n\
    \    self.assertEqual(is_sublist([2,4,3,5,7],[1,6]), False)\nAssertionError: True\
    \ != False\n"
  killer: test_is_sublist_with_2_4_3_5_7_1_6_expect_False (datasets.mbpp.tests.test_021.TestVersion)
  module: *id001
  mutations:
  - lineno: 3
    operator: ROR
  number: 10
  status: killed
  tests_run: 1
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\mbpp\\\
    tests\\test_021.py\", line 12, in test_is_sublist_with_2_4_3_5_7_1_6_expect_False\n\
    \    self.assertEqual(is_sublist([2,4,3,5,7],[1,6]), False)\nAssertionError: True\
    \ != False\n"
  killer: test_is_sublist_with_2_4_3_5_7_1_6_expect_False (datasets.mbpp.tests.test_021.TestVersion)
  module: *id001
  mutations:
  - lineno: 5
    operator: ROR
  number: 11
  status: killed
  tests_run: 1
  time: 0.0011744499206542969
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\mbpp\\\
    tests\\test_021.py\", line 9, in test_is_sublist_with_2_4_3_5_7_4_3_expect_True\n\
    \    self.assertEqual(is_sublist([2,4,3,5,7],[4,3]), True)\nAssertionError: False\
    \ != True\n"
  killer: test_is_sublist_with_2_4_3_5_7_4_3_expect_True (datasets.mbpp.tests.test_021.TestVersion)
  module: *id001
  mutations:
  - lineno: 7
    operator: ROR
  number: 12
  status: killed
  tests_run: 3
  time: 0.0009999275207519531
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 7
    operator: ROR
  number: 13
  status: survived
  tests_run: 3
  time: 0.0009989738464355469
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\mbpp\\\
    tests\\test_021.py\", line 12, in test_is_sublist_with_2_4_3_5_7_1_6_expect_False\n\
    \    self.assertEqual(is_sublist([2,4,3,5,7],[1,6]), False)\n  File \"datasets.mbpp.programs.program_021\"\
    , line 13, in is_sublist\nIndexError: list index out of range\n"
  killer: test_is_sublist_with_2_4_3_5_7_1_6_expect_False (datasets.mbpp.tests.test_021.TestVersion)
  module: *id001
  mutations:
  - lineno: 11
    operator: ROR
  number: 14
  status: killed
  tests_run: 1
  time: 0.0020639896392822266
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\mbpp\\\
    tests\\test_021.py\", line 9, in test_is_sublist_with_2_4_3_5_7_4_3_expect_True\n\
    \    self.assertEqual(is_sublist([2,4,3,5,7],[4,3]), True)\nAssertionError: False\
    \ != True\n"
  killer: test_is_sublist_with_2_4_3_5_7_4_3_expect_True (datasets.mbpp.tests.test_021.TestVersion)
  module: *id001
  mutations:
  - lineno: 13
    operator: ROR
  number: 15
  status: killed
  tests_run: 3
  time: 0.0010006427764892578
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\mbpp\\\
    tests\\test_021.py\", line 9, in test_is_sublist_with_2_4_3_5_7_4_3_expect_True\n\
    \    self.assertEqual(is_sublist([2,4,3,5,7],[4,3]), True)\n  File \"datasets.mbpp.programs.program_021\"\
    , line 13, in is_sublist\nIndexError: list index out of range\n"
  killer: test_is_sublist_with_2_4_3_5_7_4_3_expect_True (datasets.mbpp.tests.test_021.TestVersion)
  module: *id001
  mutations:
  - lineno: 13
    operator: ROR
  number: 16
  status: killed
  tests_run: 3
  time: 0.0009577274322509766
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\mbpp\\\
    tests\\test_021.py\", line 6, in test_is_sublist_with_2_4_3_5_7_3_7_expect_False\n\
    \    self.assertEqual(is_sublist([2,4,3,5,7],[3,7]), False)\nAssertionError: True\
    \ != False\n"
  killer: test_is_sublist_with_2_4_3_5_7_3_7_expect_False (datasets.mbpp.tests.test_021.TestVersion)
  module: *id001
  mutations:
  - lineno: 13
    operator: ROR
  number: 17
  status: killed
  tests_run: 2
  time: 0.001991748809814453
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\mbpp\\\
    tests\\test_021.py\", line 6, in test_is_sublist_with_2_4_3_5_7_3_7_expect_False\n\
    \    self.assertEqual(is_sublist([2,4,3,5,7],[3,7]), False)\nAssertionError: True\
    \ != False\n"
  killer: test_is_sublist_with_2_4_3_5_7_3_7_expect_False (datasets.mbpp.tests.test_021.TestVersion)
  module: *id001
  mutations:
  - lineno: 15
    operator: ROR
  number: 18
  status: killed
  tests_run: 2
  time: 0.0010008811950683594
number_of_tests: 3
targets:
- datasets.mbpp.programs.program_021
tests:
- name: datasets.mbpp.tests.test_021
  target: null
  time: 0.0
time_stats:
  create_mutant_module: 0.0010001659393310547
  create_target_ast: 0.0020012855529785156
  mutate_module: 5.1966233253479
  run_tests_with_mutant: 5.062204837799072
total_time: 5.204138994216919
